version: '3'

services:
  openproject:
    container_name: 'openproject'
    image: 'openproject/community:8'
    restart: 'always'
    env_file:
      - openproject.env
    ports:
      - '80:80'
    volumes:
      - openproject_pgdata:/var/openproject/pgdata
      - openproject_static:/var/openproject/assets
    network_mode: host

volumes:
  openproject_pgdata:
    driver: 'local'
  openproject_static:
    driver: 'local'
